# Autogenerated wrapper script for GASNet_conduit_smp_jll for x86_64-apple-darwin
export gasnet_h, libgasnet_smp_par, libgasnet_smp_parsync, libgasnet_smp_seq

JLLWrappers.@generate_wrapper_header("GASNet_conduit_smp")
JLLWrappers.@declare_file_product(gasnet_h)
JLLWrappers.@declare_library_product(libgasnet_smp_par, "@rpath/libgasnet-smp-par.dylib")
JLLWrappers.@declare_library_product(libgasnet_smp_parsync, "@rpath/libgasnet-smp-parsync.dylib")
JLLWrappers.@declare_library_product(libgasnet_smp_seq, "@rpath/libgasnet-smp-seq.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        gasnet_h,
        "include/gasnet.h",
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_par,
        "lib/libgasnet-smp-par.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_parsync,
        "lib/libgasnet-smp-parsync.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_seq,
        "lib/libgasnet-smp-seq.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
