# Autogenerated wrapper script for GASNet_conduit_smp_jll for x86_64-linux-musl
export gasnet_h, libgasnet_smp_par, libgasnet_smp_parsync, libgasnet_smp_seq

JLLWrappers.@generate_wrapper_header("GASNet_conduit_smp")
JLLWrappers.@declare_file_product(gasnet_h)
JLLWrappers.@declare_library_product(libgasnet_smp_par, "libgasnet-smp-par.so")
JLLWrappers.@declare_library_product(libgasnet_smp_parsync, "libgasnet-smp-parsync.so")
JLLWrappers.@declare_library_product(libgasnet_smp_seq, "libgasnet-smp-seq.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        gasnet_h,
        "include/gasnet.h",
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_par,
        "lib/libgasnet-smp-par.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_parsync,
        "lib/libgasnet-smp-parsync.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgasnet_smp_seq,
        "lib/libgasnet-smp-seq.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
